import uuid
from typing import Dict, List, Type, Any


class Component:
    """Marker base class for all components. Concrete components are dataclasses."""
    pass


class Entity:
    def __init__(self, name: str = None):
        self.id = uuid.uuid4()
        self.name = name or str(self.id)
        self.components: Dict[Type[Component], Component] = {}

    def add_component(self, component: Component):
        self.components[type(component)] = component
        return self

    def get_component(self, component_type: Type[Component]) -> Any:
        return self.components.get(component_type)

    def has_component(self, component_type: Type[Component]) -> bool:
        return component_type in self.components


class World:
    def __init__(self):
        self.entities: Dict[uuid.UUID, Entity] = {}
        # Global simulation clock, owned by the time_season system. Not an
        # ECS component since it describes the world itself, not an entity.
        self.current_time: float = 0.0
        self.day_count: int = 0
        self.current_season: str = None
        # Also not an ECS component - a sparse tile grid, set up by the
        # engine from config. See core/terrain.py.
        self.terrain = None
        # Chunk coordinates already generated by core/worldgen.py, so the
        # infinite world doesn't regenerate (and re-scatter resources into)
        # the same area twice.
        self.loaded_chunks: set = set()
        # Set once (randomly, unless config overrides it) by the engine on
        # a fresh world and persisted from then on, so exploring further
        # after a reload keeps generating the same world it always would
        # have - only a brand new game gets a new random seed.
        self.worldgen_seed = None
        # Static content (like the engine's self.recipes), not save-data:
        # loaded once by the engine and never touched by reset_from(), so a
        # reload doesn't wipe it. Lives on World (not the engine) because
        # systems like TreeGrowthSystem only ever see `world`, never the
        # engine itself.
        self.resource_types: dict = {}

    def reset_from(self, other: "World") -> None:
        """Copies another World's data into this one in place, instead of
        replacing the object. Some systems (e.g. NpcAutonomySystem) capture
        a `world` reference once at setup() and read it from event handlers
        outside the normal per-tick update(world, ...) call - if a reload
        swapped in a brand new World object, those captured references
        would silently go stale. Keeping the object identity fixes that for
        every such system, present and future, in one place."""
        self.entities = other.entities
        self.current_time = other.current_time
        self.day_count = other.day_count
        self.current_season = other.current_season
        self.terrain = other.terrain
        self.loaded_chunks = other.loaded_chunks
        self.worldgen_seed = other.worldgen_seed

    def create_entity(self, name: str = None) -> Entity:
        entity = Entity(name)
        self.entities[entity.id] = entity
        return entity

    def get_entity_by_name(self, name: str) -> "Entity | None":
        return next((e for e in self.entities.values() if e.name == name), None)

    def get_entities_with_components(self, *component_types: Type[Component]) -> List[Entity]:
        return [
            e for e in self.entities.values()
            if all(e.has_component(ct) for ct in component_types)
        ]
